const scents = [
  "Ambre",
  "Mousse d'arbre",
  "Fleur de Citronnier",
  "Banane",
  "Baies de genévrier",
  "Bigarade",
  "Orchidée",
  "Cascarille",
  "Muscs blancs",
  "Gentiane",
  "Note aqueuse",
  "Feuilles d'Ajonc",
  "Bergamote",
  "Epices",
  "Framboise",
  "Glycine",
  "Champagne Rosé",
  "Evernyl",
  "Gardénia",
  "Gurjan",
  "Notes fumées",
  "Orange",
  "Caramel",
  "Mûre",
  "Mangue",
  "Eau de Rose",
  "Tubéreuse",
  "Akigalawood®",
  "Tabac",
  "Oliban",
  "Cuir",
  "Cannabis",
  "Cyclamen",
  "Estragon",
  "Laurier",
  "Pain",
  "Poivre",
  "Palo Santo",
  "Silex",
  "Thym",
  "Amande amère",
  "Immortelle",
  "Nashi pear",
  "Safran",
  "Petitgrain",
  "Dahlia",
  "Freesia",
  "Macchiato",
  "Piña Colada",
  "Fleur d'Oranger",
  "Buchu",
  "Dragée",
  "Cyprès",
  "Hédione",
  "Cerise",
  "Ambroxan",
  "Cire d'abeille",
  "Popcorn",
  "Notes de Pluie",
  "Poivre Rose",
  "Chocolat",
  "Baies roses",
  "Eau de mer",
  "Concombre",
  "Praline",
  "Ebene",
  "Romarin",
  "Galbanum",
  "Maninka",
  "Cypriol",
  "Accord aromatique",
  "Hibiscus",
  "Poudre à canon",
  "Bellini",
  "Costus",
  "Fève tonka",
  "Bois",
  "Cassie",
  "Algue",
  "Pin",
  "Cannelle",
  "Ambrette",
  "Figuier",
  "Nénuphar",
  "Notes balsamiques",
  "Eucalyptus",
  "Ylang-Ylang",
  "Narcisse",
  "Carvi",
  "Lait chaud",
  "Iris",
  "Fruits d'eau",
  "Amyris",
  "Myrtille",
  "Citronnelle",
  "Orange Verte",
  "Gingembre",
  "Karo karoundé",
  "Ozone",
  "Basilic",
  "Vanille",
  "Cranberry",
  "Notes Rosées",
  "Notes suaves",
  "Hortensia",
  "Trèfle",
  "Mojito",
  "Notes orientales",
  "Pivoine",
  "Néroli",
  "Piment",
  "Châtaigne",
  "Fir balsam",
  "Myrrhe",
  "Bambou",
  "Magnolia",
  "Pistache",
  "Amande",
  "Reine de la Nuit",
  "Cédrat",
  "Grenade",
  "Osmanthus",
  "Anis",
  "Pavot",
  "Musc",
  "Lavande",
  "Fraise",
  "Champaca",
  "Macaron",
  "Cumin",
  "Fleurs Blanches",
  "Jasmin",
  "Marjolaine",
  "Pittosporum",
  "Badiane",
  "Coing",
  "férule gommeuse",
  "Bois de Cachemire",
  "Daim",
  "Dihydromyrcénol",
  "Clémentine",
  "Sable Chaud",
  "Musc tonkin",
  "Bois de gaiac",
  "Pure Malt",
  "bougainvillier",
  "Céleri",
  "Pitaya",
  "Lemongrass",
  "Noisette",
  "Coumarine",
  "Fruits secs",
  "Ciste",
  "Pois de senteur",
  "Vanilline",
  "Hysope",
  "Patchouli",
  "Tiaré",
  "Cognac",
  "notes terreuses",
  "Vétiver",
  "Notes Minérales",
  "Sésame",
  "Acajou",
  "Aneth",
  "MUGU",
  "Notes solaires",
  "Feuille de mandarinier",
  "Truffe",
  "Lotus",
  "Limette",
  "Pastèque",
  "Rhubarbe",
  "Violette",
  "Raisin",
  "Héliotrope",
  "Lavandin",
  "Dattes",
  "son de blé",
  "Poire",
  "Agrumes",
  "Ambre gris",
  "Frangipanier",
  "Bois ambrés",
  "Baume Pérou",
  "Cardamome",
  "Curcuma",
  "Inconnu",
  "Aubépine",
  "Feuille de tomate",
  "Géranium",
  "Sel de mer",
  "Note Fruitée",
  "Guimauve",
  "Ananas",
  "Datura",
  "Pruneau",
  "Fruit de la passion",
  "Mirabilis",
  "Riz",
  "Mimosa",
  "Aldéhydes",
  "Paradisone",
  "Iso E Super",
  "Abricot",
  "Mousse de chêne",
  "Camomille romaine",
  "Fleurs Exotiques",
  "Sucre",
  "Fleurs de palmier",
  "Cassis",
  "Macis",
  "Cappuccino",
  "Myrte",
  "Lierre",
  "Lilas",
  "Oxyde de rose",
  "Papaye",
  "Kiwi",
  "Groseille",
  "Réglisse",
  "Fruits Rouges",
  "Mirabelle",
  "Mangoustan",
  "Calamus",
  "Tulipe",
  "Tagète",
  "Noix de coco",
  "Résine",
  "Prune",
  "Pêche",
  "Feuille de vigne",
  "Sauge sclarée",
  "Tangerine",
  "Citron",
  "Chêne",
  "Girofle",
  "Civette",
  "Notes poudrées",
  "Litchi",
  "Pamplemousse",
  "Genêt",
  "Lie de vin",
  "Lys",
  "Quisqualier",
  "Thé Noir",
  "Pomme",
  "Coriandre",
  "Thé",
  "Corbeille de fruits",
  "Belle de Nuit",
  "Styrax",
  "Noix de muscade",
  "Chèvrefeuille",
  "Bois de rose",
  "Orcanox",
  "Notes Boisées",
  "Dulce de Leche",
  "Armoise",
  "Barbe à papa",
  "Verveine",
  "Castoreum",
  "Sel",
  "Fenouil",
  "Angélique",
  "undefined",
  "Feuille de violette",
  "Opopanax",
  "Figue",
  "Kumquat",
  "Crème fouettée",
  "Bouleau",
  "Jonquille",
  "Accord herbe de bison",
  "Ginseng",
  "agathosma",
  "Note marine",
  "Elemi",
  "Menthe",
  "Nectarine",
  "Bois de Hêtre",
  "Encens",
  "Fleur de Cerisier",
  "Rose",
  "Notes fleuries",
  "Baies de Goji",
  "Davana",
  "Absinthe",
  "Limoncello",
  "Animalis",
  "Oud",
  "Baume Tolu",
  "Cèdre",
  "Cannellier Feuille",
  "Seringa",
  "Eau de vie",
  "Lentisque",
  "Cashmeran",
  "Genièvre",
  "Oeillet",
  "Foin",
  "Fruits Exotiques",
  "Muguet",
  "Note animale",
  "Champagne",
  "Santal",
  "Yuzu",
  "Lait d'Amande",
  "Sorbet",
  "Note verte",
  "Melon",
  "Caviar",
  "Feuille de Cèdre",
  "Cade",
  "Café",
  "Labdanum",
  "Goyave",
  "papyrus",
  "Rhum",
  "Miel",
  "Baume",
  "Carotte",
  "Pomme d'Amour",
  "Maté",
  "Benjoin",
  "Poivre noir",
  "Jacinthe",
  "Shiso",
  "Calypsone",
  "Cacao",
  "coton",
  "Accord Chypré",
  "Bois de Chêne",
  "Mandarine",
  "Notes métalliques",
  "Bourgeon de cassis",
];
